Feature/products list api
wecode-bootcamp-korea/39-1st-naweke-backend pull request #10
Opened 2022-11-19 04:24 UTC by lukas0306

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
상품 목록 필터링 및 정렬 기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
성, 메인 카테고리, 서브 카테고리, 색상, 사이즈, 가격대 별 필터링 
가격 별 오름차순, 내림차순 정렬
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
where절에 들어갈 필터기능들이 많아서 어떻게 구현해야 할 지 고민이 많았는데 굉장히 억지로 필터링을 구현했고
그 과정에서 나름 공부가 많이 된 것 같습니다.

<br />

## :: 기타 질문 및 특이 사항
현재 models 레이어에서 처리하고 있는 로직들을 서비스 레이어로 옮기고 where절 조건들을 모듈화 시켜서
정리하는 것을 주말동안 시도해보겠습니다.

2022-11-20 12:30 UTC, lukas0306 commented
where절 조건들 모듈화해서 리팩토링하였고 size나 색상 같은 필터 여러개 넣는 것( ex) size=220&size=230)을 구현하지 못해서 추가 구현 예정입니다.

2022-11-20 13:33 UTC, lukas0306 commented
size filter 여러개 넣기 추가했습니다.

2022-11-22 02:32 UTC, bigfanoftim requested changes
- 리뷰를 보다보니 기존에 있던 것을 없애고 새로 만든다던지 하는 오류가 좀 있어보입니다. 컨플릭트 먼저 해결하시면 그때 리뷰하겠습니다. 
- PR을 올리신 후에는 반드시 PR에 있는 `Files changed` 탭을 눌러 본인이 의도한 방향으로 코드가 잘 작성되었는지 확인해야 합니다.
- PR 올리기 전 각자 사용하고 있는 IDE(Vim, Vscode, WebStrom, IntelliJ 등)에서 Git 변경 사항을 체크하는 것도 좋은 방법입니다.

2022-11-22 02:32 UTC, bigfanoftim commented on src/routes/productRouter.js
> +productRouter.get('/all', productController.getAllProducts);
```suggestion
productRouter.get('', productController.getAllProducts);
```
`all`은 굳이 적어주지 않아도 될 것 같아요~ 실제로 모든 product를 보여주는 것은 아니니까요. 굳이 바꾼다면 list가 있겠습니다만 그것도 굳이? 라는 생각이 드네요 ㅎㅎ

2022-11-22 03:46 UTC, lukas0306 commented
깃 충돌해결하고 라우터 주소 변경했습니다!

2022-11-22 05:28 UTC, bigfanoftim requested changes

2022-11-22 05:28 UTC, bigfanoftim commented on src/services/productService.js
> +  }
req를 검증하는 작업은 controller에서 해주시면 되겠습니다~

2022-11-22 05:28 UTC, bigfanoftim commented on src/utils/productQueryBuilder.js
> +    return `po.price >= 200000`;
변경이 일어날 수 있는 값은 하드코딩을 피해주세요.

2022-11-22 05:28 UTC, bigfanoftim commented on src/services/productService.js
> +      throw err;
예외처리에서 반복되는 이 3줄을 따로 모듈화하는 것은 어떨까요?

```JavaScript
const raiseCustomError = (message, statusCode) => {
  const err = new Error(message);
  err.statusCode = statusCode;
  throw err
}
```

이렇게라도 간단히 작성해놓으면 계속해서 반복되는 코드를 이 함수하나로 대체할 수 있을 것 같습니다.

2022-11-22 06:44 UTC, lukas0306 commented
에러처리 모듈화하였습니다.

2022-11-22 06:47 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-22 06:47 UTC, merged