Feature/likes
wecode-bootcamp-korea/39-1st-naweke-backend pull request #11
Opened 2022-11-19 14:55 UTC by lukas0306

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
상품 추천 api

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
추천한 상품의 id가 존재 하지 않을 시 예외 처리.
이미 추천을 한 상품에 다시 추천 할 경우 취소 처리.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
.

<br />

## :: 기타 질문 및 특이 사항
현재 유저의 아이디를 path params로 받아오고 있는데 토큰에서 decode한 아이디로 대체할 예정입니다.

2022-11-22 07:43 UTC, lukas0306 commented
branch 삭제 후 다시 만들어서  올렸습니다.

2022-11-22 08:10 UTC, bigfanoftim requested changes
Files changed 확인 후 불필요한 console.log 전부 지워주세요~

2022-11-22 08:10 UTC, bigfanoftim commented on src/controllers/productController.js
> +module.exports = { loadProductInfo, getAllProducts };
👀

2022-11-22 08:10 UTC, bigfanoftim commented on src/models/likeDao.js
> +};
이건 productDao에 있어야 하지 않을까요?

2022-11-22 08:10 UTC, bigfanoftim commented on src/models/likeDao.js
> +const checkExistence = async (userId, productId) => {
```suggestion
const getLike = async (userId, productId) => {
```

2022-11-22 08:10 UTC, bigfanoftim commented on src/models/likeDao.js
> +const cancelpostLike = async (userId, productId) => {
```suggestion
const deleteLike = async (userId, productId) => {
```

2022-11-24 06:07 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 06:07 UTC, merged