ADD:post/delete Review
wecode-bootcamp-korea/39-1st-naweke-backend pull request #17
Opened 2022-11-22 07:50 UTC by lukas0306

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />
리뷰 작성과 삭제 API입니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
해당 상품 체크, 이미 리뷰한 상품인지에 대한 예외 처리

<br />

.

<br />

## :: 기타 질문 및 특이 사항
리뷰 수정도 추가할 예정입니다!

2022-11-23 02:16 UTC, bigfanoftim requested changes
불필요한 console.log()가 있거나 네이밍을 크게 중요하게 생각하지 않고 코드를 작성하신 느낌이 듭니다.
PR을 올리신 후에는 반드시 PR에 있는 `Files changed` 탭을 눌러 본인이 의도한 방향으로 코드가 잘 작성되었는지 확인해야 합니다.

2022-11-23 02:16 UTC, bigfanoftim commented on src/controllers/reviewController.js
> +  const { productId, title, content, image_url } = req.body;
```suggestion
  const { productId, title, content, image_url } = req.body;
  
  if ( !productId || !title || !content || !imageUrl ) { ... }
```
body에 의도한 값이 들어오지 않았을 때의 예외 처리를 해주세요.

2022-11-23 02:16 UTC, bigfanoftim commented on src/controllers/reviewController.js
> +const cancelReview = async (req, res) => {
```suggestion
const deleteReview = async (req, res) => {
```

2022-11-23 02:16 UTC, bigfanoftim commented on src/controllers/reviewController.js
> +  const { productId, title, content, image_url } = req.body;
모든 네이밍 컨벤션이 동일해야 합니다. (CamelCase, snake_case를 섞어서 사용하면 안됨)

2022-11-23 02:16 UTC, bigfanoftim commented on src/services/reviewService.js
> +  const checkId = await reviewDao.getReviewId(productId);
상품에 리뷰를 등록하기 위해 리뷰 ID를 가져오는 것이 아니라 상품의 존재 여부를 판단하는 것 같은데 그럼 네이밍이 잘못되지 않았나요?
그리고 지금 작성한 로직은 그 의미가 product에 대한 정보를 가져오는 것이니 reviewDao가 아니라 productDao에 넣어야 합니다.

2022-11-23 02:16 UTC, bigfanoftim commented on src/models/reviewDao.js
> +      `,
id를 가져올 필요가 없을 것 같아요. 애초에 알고 있으니 다시 리턴받을 필요가 없습니다. 그저 EXISTS로 존재 여부만 봐도 좋을 것 같습니다.

2022-11-23 02:16 UTC, bigfanoftim commented on src/models/reviewDao.js
> +  console.log(userId, productId);
```suggestion
```

2022-11-23 02:16 UTC, bigfanoftim commented on src/services/reviewService.js
> +  const checkList = Number(reviewData?.checkList);
checkList가 무엇을 의미하는 걸까요? 제가 아는 체크리스트는 이런 느낌이 아닌 것 같습니다.

2022-11-24 07:06 UTC, bigfanoftim requested changes
migration 파일이 지워졋는데 혹시 맞는건가요?

만약 불필요한 테이블이 있어서 지우고 싶다면 새로운 마이그레이션 파일을 만들어서 지워주세요.

2022-11-24 07:06 UTC, bigfanoftim commented on src/utils/filterSet.js
> +
```JavaScript
const genderSet = Object.freeze({ ... })
```
이렇게 수정해 주세요~

2022-11-24 07:26 UTC, lukas0306 commented
똑같은 테이블을 만드는 마이그레이션이 3개였어서 2개를 지웠습니다!

2022-11-24 07:47 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 07:47 UTC, merged