[ADD] 장바구니 수량 변경 기능 추가
wecode-bootcamp-korea/39-1st-naweke-backend pull request #19
Opened 2022-11-23 04:06 UTC by applleeee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니에서 상품의 수량 변경 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니에 담긴 상품의 수량을 1부터 7 사이의 숫자로 선택 후 변경.
 - 수량이 8 이상일 때 에러
 - 해당 상품이 있는지 체크 후 없으면 에러
 - 위 사항을 만족하면 수량 수정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 여러 예외 상황들을 가정하고 그에 따른 처리를 해주었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-11-23 06:52 UTC, bigfanoftim requested changes
피드백 확인 후 전체적으로 한번 수정해주세요.
그리고 지난 피드백과 마찬가지로 메소드 이름에 controller, service 전부 지워주세요~

2022-11-23 06:52 UTC, bigfanoftim commented on src/routes/cartsRouter.js
> +cartsRouter.patch('/quantity', validateAccessToken, modifyQuantityController);
```suggestion
cartsRouter.patch('/:cartId', validateAccessToken, modifyQuantityController);
```
특정 장바구니 데이터를 변경하는 것이기 때문에 body에 quantity만 받고 query param으로 cartId를 받는 것은 어떨까요?

```JavaScript
// cart 수정 API

// 👍 - 한 눈에 1번 카트를 수정하는 것을 알 수 있음
PATCH :3000/carts/1
```

2022-11-23 06:52 UTC, bigfanoftim commented on src/controllers/cartsController.js
> +  const { productOptionId } = req.query;
송현님 혹시 이 코드 테스트 해보신건가요?

2022-11-23 07:06 UTC, applleeee commented on src/controllers/cartsController.js
> +  const { productOptionId } = req.query;
http://localhost:3000/carts/quantity?productOptionId=8
넵 원래 이렇게 테스트 했었는데 위에 말씀해주신 대로 수정할 때 같이 수정하겠습니다.

2022-11-24 06:11 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-24 06:11 UTC, merged