[ADD] Feature/order
wecode-bootcamp-korea/39-1st-naweke-backend pull request #9
Opened 2022-11-18 17:15 UTC by myeongseoklee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카트에 담긴 상품을 주문하는 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카트에 담긴 상품을 주문하는 API 구현
- 장바구니에는 최종 구매할 상품만을 골라서(select) 주문할 수 있도록 구현이 되어 있지 않습니다. 즉 장바구니에서는 장바구니에 담은 물건을 모두 구매해야만 하도록 구현이 될 예정입니다.
- 그래서 구매를 희망하지 않는다면 장바구니에서 해당 상품을 삭제해야 합니다.(그래서 삭제 버튼 옆에는 위시리스트로 해당 상품을 보내는 버튼이 있습니다.)
- 결국, 장바구니에서 주문하기 버튼을 누르면 장바구니에 담긴 모든 상품을 구매하게 됩니다.
- 구매 이후 로직은 보통 구매하기 -> 결제 -> 배송주소 입력 -> 결제 완료의 과정을 거치지만, 현 프로젝트에서는 장바구니에서 order가 내려지면 바로 결제 완료(order_status와 order_items_status 모두)가 됩니다.
- 따라서, 상품 주문 이후에는 데이터베이스 carts 테이블에 담겨있는 모든 상품 중 유저가 구매한 상품은 삭제되게 됩니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
[어려웠던 점]
1. 쿼리문을 작성하는 것이 어려웠습니다. orderDao의 함수에서 join을 중복하여 사용하거나, sub query 등을 사용하여 적은 함수를 사용하고, orderService 에서의 로직을 가독성 좋게 작성하고 싶었지만, 쿼리문 작성이 쉽지 않았습니다. 우선 기능 구현에 우선순위를 두고, orderDao는 아주 기초적인 수준의 쿼리문으로 작성하였고 비즈니스 로직에서 주로 필요한 처리를 했습니다.
2. 트랜젝션을 활용하여 구현할 수 있을까 하여 찾아보았지만 해당 개념에 대해 이해하기 어려워 시도하지 못했습니다.

[성장점]
1. Insert 쿼리문 실행으로 리턴되는 결과 객체 안에 있는 insertId 키의 값을 활용하여 두 함수를 연결할 수 있다는 점을 배웠습니다.

[추가적으로 필요한 구현사항]
1. 주문 된 재고를 줄이는 로직을 추가해야 합니다.
2. orderDao에서 deleteOrderedItemsInCart 함수에서, 카트에 있는 상품을 user_id 일치 뿐만 아니라, cart와 order_items의 상품 옵션 id도 일치할 때 삭제 되도록 로직을 추가해야 합니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-11-21 16:26 UTC, myeongseoklee commented
for문으로 직접 dao에 접근하면, 주문 할 상품이 극단적으로 많을 경우 database에 무리를 줄 수 있다는 피드백을 주셨습니다.
그래서 구글링해보니, bulk insert와 bulk update의 개념이 있어, 서비스단에서 query문을 for loop를 활용해 동적으로 변수에 담아 dao로 넘겨주었습니다.

2022-11-22 02:26 UTC, bigfanoftim requested changes

2022-11-22 02:26 UTC, bigfanoftim commented on src/services/orderService.js
> +  Object.freeze(orderItemStatus);
```JavaScript
const orderStatus = Object.freeze({ ... })
```

2022-11-22 02:26 UTC, bigfanoftim commented on src/services/orderService.js
> +  };
src/ 디렉토리 최상위에 `enum.js`로 따로 분리하는 것이 더 좋겠습니다.

2022-11-22 02:26 UTC, bigfanoftim commented on src/services/orderService.js
> +  }
우선 query build를 위한 코드들은 전부 model layer로 이동시켜주세요. 
보통 bulk 같은 코드는 재활용되기 때문에 `src/models/utils/`와 같은 위치에 따로 모듈로 관리하는 것이 좋습니다.

그리고 지금 로직을 보면 cart에서 정보를 가져오는데 이렇게 되면 제가 말씀드렸던 것처럼 cart를 통하지 않고서는 절대 구매로 이어질 수 없는 구조입니다. 저희가 cart에서 정보를 가져올 필요없이 카트에 담긴 product와 관련된 정보들을 클라이언트로 부터 받아서 처리해 주세요.

2022-11-22 05:55 UTC, myeongseoklee commented
- enum은 따로 모듈화한 후 필요한 곳에 import하였습니다.
- 상세페이지에서 바로 결제 기능으로도 활용할 수 있도록 cart에서 데이터를 받아오지 않고 프론트에서 직접 받는 방식으로 재구현하였습니다.
- service로직에 있던 bulk query를 dao로 이전 하였습니다.

2022-11-22 06:45 UTC, bigfanoftim requested changes

2022-11-22 06:45 UTC, bigfanoftim commented on src/models/orderDao.js
> +};
```JavaScript
const arr = ["(1, 10, 1)", "(1, 5, 3)", "(1, 6, 4)"]

const values = arr.join(", ")

console.log(
  `
    INSERT INTO order_itmes (
      order_id,
      product_id,
      quantity
    ) VALUES 
      ${values}
  `
)

```

2022-11-22 15:16 UTC, myeongseoklee commented
말씀해주신대로 orderDao에 transaction 적용 및 insert 로직을 수정하였습니다.
다만, 재고를 수정하는 update query의 로직도 개선을 시도했지만 단순한 구조로 구성하는 것에 실패하였습니다. 도움요청드립니다.

2022-11-23 02:44 UTC, bigfanoftim requested changes
나머지도 다 비슷한 맥락입니다.
map을 사용했을 때 어떤식으로 결과가 나오는지 따로 javascript파일 만들어서 테스트해보시는 것이 좋아보입니다.

2022-11-23 02:44 UTC, bigfanoftim commented on src/models/orderDao.js
> +    values = valuesQuery(orderArr, values).join(',');
```suggestion
    const valuesQuery = (data) => {
      return data.map((obj) => {
          return `(${order.insertId}, ${
            orderItemStatus.DELIVERYCOMPLETED
          }, ${Object.values(obj)})`
      });
    };
    const valueSet = valuesQuery(orderArr).join(',');
```

코드를 조금 더 정확히 수정해봐야 알겠지만 애초에 map을 썻으면 위에 불필요하게 빈리스트를 만들 필요가 없습니다.
넣어줄 data를 받으면 그에 맞는 value set을 만들어주기만 하면 될 것 같습니다.

2022-11-23 04:47 UTC, myeongseoklee commented on src/models/orderDao.js
> +    values = valuesQuery(orderArr, values).join(',');
map 메소드가 리턴하는 값을 어떻게 변수에 담아야할 지 고민이었습니다. 도움 감사드립니다!

2022-11-23 06:01 UTC, bigfanoftim requested changes

2022-11-23 06:01 UTC, bigfanoftim commented on src/controllers/productController.js
> +module.exports = { loadProductInfo, getAllProducts };
👀

2022-11-23 06:04 UTC, myeongseoklee commented on src/controllers/productController.js
> +module.exports = { loadProductInfo, getAllProducts };
삭제했습니다!

2022-11-23 07:11 UTC, bigfanoftim requested changes

2022-11-23 07:11 UTC, bigfanoftim commented on src/controllers/orderController.js
> +    return res.status(201).json({ message: 'order Created' });
```suggestion
    const userId = req.decoded;
    const { totalPrice, orderItems } = req.body;
    
    await createOrder(userId, orderItems, totalPrice);
    
    return res.status(201).json({ message: 'order Created' });
```
지금보니 구문이 굉장히 어색하네요. 애초에 전달받고자 하는 데이터 형태를 잘 정돈해놔야 받아서 활용할 때 간단히 활용할 수 있습니다.

2022-11-23 07:11 UTC, bigfanoftim commented on src/controllers/orderController.js
> +    return res.status(201).json({ message: 'order Created' });
```JSON
{
    "totalPrice" : 250000,
    "orderItems" : [
        {
            "id"              : 1,
            "productOptionId" : 2,
            "quantity"        : 1
        },
        {
            "id"              : 1,
            "productOptionId" : 2,
            "quantity"        : 1
        }
    ]
}

```

2022-11-23 07:11 UTC, bigfanoftim commented on src/models/orderDao.js
> +    const conditionQuery = (data, i) => {
conditionQuery는 정확히 무엇을 하는 함수인가요? 이름만 봐서는 파악하기가 쉽지가 않네요..

좋은 코드는 이름과 인터페이스만 보고도 활용할 수 있도록 작성하는 것입니다. 또한 함수는 일종의 동작이기 때문에 동사를 활용해서 작성하는 것이 더 좋습니다.
```JavaScript
// 👍
const buildInsertQuery = ( .. ) => { ... }
// 👍
const createInsertQuery = ( .. ) => { ... }

// 💩
const insertQuery = ( .. ) => { ... }
```

2022-11-23 08:54 UTC, bigfanoftim approved these changes
LGTM :

2022-11-23 08:54 UTC, merged